module.exports = {
    grant_type: 'client_credential',
    mch_id: '1520782501',
    mch_key: '41134e3b985d0254c6c7c64912fc0935',
    appid: 'wx4a5e9d7ae34ad4b4',
    secret: '67ac3bcb97adf225c8b9986fb470a4a1',
    noncestr: 'Wm3WZYTPz0wzccnWsdfadf',
    accessTokenUrl:'https://api.weixin.qq.com/cgi-bin/token',
    ticketUrl:'https://api.weixin.qq.com/cgi-bin/ticket/getticket',
    cache_duration:1000*60*60*24, //缓存时长为24小时
    miniAppId: 'wx4b3efb80ac5de780',
    miniAppSecret: '36ad9a51a413cb4dbe1562206c6c0ba4',
    miniBgwAppId: 'wxdb571c43fa1ff06b',
    miniBgwAppSecret: 'ce11b91e55ec25bccff837401746717c',
    /*jsApiList: ['checkJsApi',
    'chooseImage',
    'uploadImage',
    'downloadImage',
    'previewImage',
    'scanQRCode',
    'chooseWXPay']
    */
    jsApiList: ['checkJsApi',
    'updateAppMessageShareData',
    'updateTimelineShareData',
    'onMenuShareTimeline',
    'onMenuShareAppMessage',
    'onMenuShareQQ',
    'onMenuShareWeibo',
    'hideMenuItems',
    'showMenuItems',
    'hideAllNonBaseMenuItem',
    'showAllNonBaseMenuItem',
    'translateVoice',
    'startRecord',
    'stopRecord',
    'onRecordEnd',
    'playVoice',
    'pauseVoice',
    'stopVoice',
    'uploadVoice',
    'downloadVoice',
    'chooseImage',
    'previewImage',
    'uploadImage',
    'downloadImage',
    'getNetworkType',
    'openLocation',
    'getLocation',
    'hideOptionMenu',
    'showOptionMenu',
    'closeWindow',
    'scanQRCode',
    'chooseWXPay',
    'openProductSpecificView',
    'addCard',
    'chooseCard',
    'openCard'] // 必填，需要使用的JS接口列表，
}